package wired:script;

world script {
  export lifecycle;
}

interface lifecycle {
  resource data {}

  /// Called once to initialize the script.
  init: func() -> data;

  /// Called every tick.
  update: func(data: borrow<data>);
}
