package wired:script;

world script {
  export types;
}

interface types {
  // Script resource that will be instantiated by the host.
  resource script {
    constructor();

    // Called every tick.
    update: func(delta: f32);
  }
}
