package wired:script;

world script {
  export lifecycle;
}

interface lifecycle {
  // Arbitrary script data persisted between updates.
  resource data {}

  // Called once to initialize the script.
  init: func() -> data;

  // Called every tick.
  update: func(delta: f32, data: borrow<data>);
}
