package wired:prelude;

// Prelude to be `include`d in your world for ease of use.
world imports {
  import wired:input/handler;
  import wired:log/api;
  import wired:math/types;
  import wired:physics/types;
  import wired:player/api;
  import wired:scene/material;
  import wired:scene/mesh;
  import wired:scene/node;
}

world script {
  include imports;
  include wired:script/script;
}
