name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: creyD/prettier_action@v4.5
        with:
          prettier_options: --write .

      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: lint"
          default_author: github_actions
